// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class VeilBridgeApi
    extends
        BaseEntrypoint<
          VeilBridgeApiApi,
          VeilBridgeApiApiImpl,
          VeilBridgeApiWire
        > {
  @internal
  static final instance = VeilBridgeApi._();

  VeilBridgeApi._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    VeilBridgeApiApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required VeilBridgeApiApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<VeilBridgeApiApiImpl, VeilBridgeApiWire>
  get apiImplConstructor => VeilBridgeApiApiImpl.new;

  @override
  WireConstructor<VeilBridgeApiWire> get wireConstructor =>
      VeilBridgeApiWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 287533687;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'veil_sdk_bridge',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class VeilBridgeApiApi extends BaseApi {
  Future<BigInt> crateApiCurrentEpochSeconds({
    required BigInt now,
    required BigInt epochSeconds,
  });

  Future<ObjectMeta> crateApiDecodeObjectMeta({required List<int> bytes});

  Future<ShardMeta> crateApiDecodeShardMeta({required List<int> bytes});

  Future<String> crateApiDeriveFeedTagHex({
    required String publisherPubkeyHex,
    required int namespace,
  });

  Future<String> crateApiDeriveObjectRootHex({required List<int> objectBytes});

  Future<String> crateApiDeriveRvTagHex({
    required String recipientPubkeyHex,
    required int epoch,
    required int namespace,
  });
}

class VeilBridgeApiApiImpl extends VeilBridgeApiApiImplPlatform
    implements VeilBridgeApiApi {
  VeilBridgeApiApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<BigInt> crateApiCurrentEpochSeconds({
    required BigInt now,
    required BigInt epochSeconds,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(now, serializer);
          sse_encode_u_64(epochSeconds, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCurrentEpochSecondsConstMeta,
        argValues: [now, epochSeconds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCurrentEpochSecondsConstMeta =>
      const TaskConstMeta(
        debugName: "current_epoch_seconds",
        argNames: ["now", "epochSeconds"],
      );

  @override
  Future<ObjectMeta> crateApiDecodeObjectMeta({required List<int> bytes}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_object_meta,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDecodeObjectMetaConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDecodeObjectMetaConstMeta =>
      const TaskConstMeta(debugName: "decode_object_meta", argNames: ["bytes"]);

  @override
  Future<ShardMeta> crateApiDecodeShardMeta({required List<int> bytes}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_shard_meta,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDecodeShardMetaConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDecodeShardMetaConstMeta =>
      const TaskConstMeta(debugName: "decode_shard_meta", argNames: ["bytes"]);

  @override
  Future<String> crateApiDeriveFeedTagHex({
    required String publisherPubkeyHex,
    required int namespace,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(publisherPubkeyHex, serializer);
          sse_encode_u_16(namespace, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDeriveFeedTagHexConstMeta,
        argValues: [publisherPubkeyHex, namespace],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeriveFeedTagHexConstMeta => const TaskConstMeta(
    debugName: "derive_feed_tag_hex",
    argNames: ["publisherPubkeyHex", "namespace"],
  );

  @override
  Future<String> crateApiDeriveObjectRootHex({required List<int> objectBytes}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(objectBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDeriveObjectRootHexConstMeta,
        argValues: [objectBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeriveObjectRootHexConstMeta =>
      const TaskConstMeta(
        debugName: "derive_object_root_hex",
        argNames: ["objectBytes"],
      );

  @override
  Future<String> crateApiDeriveRvTagHex({
    required String recipientPubkeyHex,
    required int epoch,
    required int namespace,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(recipientPubkeyHex, serializer);
          sse_encode_u_32(epoch, serializer);
          sse_encode_u_16(namespace, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDeriveRvTagHexConstMeta,
        argValues: [recipientPubkeyHex, epoch, namespace],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeriveRvTagHexConstMeta => const TaskConstMeta(
    debugName: "derive_rv_tag_hex",
    argNames: ["recipientPubkeyHex", "epoch", "namespace"],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  ObjectMeta dco_decode_object_meta(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 14)
      throw Exception('unexpected arr length: expect 14 but see ${arr.length}');
    return ObjectMeta(
      version: dco_decode_u_16(arr[0]),
      namespace: dco_decode_u_16(arr[1]),
      epoch: dco_decode_u_32(arr[2]),
      flags: dco_decode_u_16(arr[3]),
      signed: dco_decode_bool(arr[4]),
      public: dco_decode_bool(arr[5]),
      ackRequested: dco_decode_bool(arr[6]),
      batched: dco_decode_bool(arr[7]),
      tagHex: dco_decode_String(arr[8]),
      objectRootHex: dco_decode_String(arr[9]),
      senderPubkeyHex: dco_decode_opt_String(arr[10]),
      nonceHex: dco_decode_String(arr[11]),
      ciphertextLen: dco_decode_usize(arr[12]),
      paddingLen: dco_decode_usize(arr[13]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ShardMeta dco_decode_shard_meta(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return ShardMeta(
      version: dco_decode_u_16(arr[0]),
      namespace: dco_decode_u_16(arr[1]),
      epoch: dco_decode_u_32(arr[2]),
      tagHex: dco_decode_String(arr[3]),
      objectRootHex: dco_decode_String(arr[4]),
      k: dco_decode_u_16(arr[5]),
      n: dco_decode_u_16(arr[6]),
      index: dco_decode_u_16(arr[7]),
      payloadLen: dco_decode_usize(arr[8]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  ObjectMeta sse_decode_object_meta(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_version = sse_decode_u_16(deserializer);
    var var_namespace = sse_decode_u_16(deserializer);
    var var_epoch = sse_decode_u_32(deserializer);
    var var_flags = sse_decode_u_16(deserializer);
    var var_signed = sse_decode_bool(deserializer);
    var var_public = sse_decode_bool(deserializer);
    var var_ackRequested = sse_decode_bool(deserializer);
    var var_batched = sse_decode_bool(deserializer);
    var var_tagHex = sse_decode_String(deserializer);
    var var_objectRootHex = sse_decode_String(deserializer);
    var var_senderPubkeyHex = sse_decode_opt_String(deserializer);
    var var_nonceHex = sse_decode_String(deserializer);
    var var_ciphertextLen = sse_decode_usize(deserializer);
    var var_paddingLen = sse_decode_usize(deserializer);
    return ObjectMeta(
      version: var_version,
      namespace: var_namespace,
      epoch: var_epoch,
      flags: var_flags,
      signed: var_signed,
      public: var_public,
      ackRequested: var_ackRequested,
      batched: var_batched,
      tagHex: var_tagHex,
      objectRootHex: var_objectRootHex,
      senderPubkeyHex: var_senderPubkeyHex,
      nonceHex: var_nonceHex,
      ciphertextLen: var_ciphertextLen,
      paddingLen: var_paddingLen,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ShardMeta sse_decode_shard_meta(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_version = sse_decode_u_16(deserializer);
    var var_namespace = sse_decode_u_16(deserializer);
    var var_epoch = sse_decode_u_32(deserializer);
    var var_tagHex = sse_decode_String(deserializer);
    var var_objectRootHex = sse_decode_String(deserializer);
    var var_k = sse_decode_u_16(deserializer);
    var var_n = sse_decode_u_16(deserializer);
    var var_index = sse_decode_u_16(deserializer);
    var var_payloadLen = sse_decode_usize(deserializer);
    return ShardMeta(
      version: var_version,
      namespace: var_namespace,
      epoch: var_epoch,
      tagHex: var_tagHex,
      objectRootHex: var_objectRootHex,
      k: var_k,
      n: var_n,
      index: var_index,
      payloadLen: var_payloadLen,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_object_meta(ObjectMeta self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.version, serializer);
    sse_encode_u_16(self.namespace, serializer);
    sse_encode_u_32(self.epoch, serializer);
    sse_encode_u_16(self.flags, serializer);
    sse_encode_bool(self.signed, serializer);
    sse_encode_bool(self.public, serializer);
    sse_encode_bool(self.ackRequested, serializer);
    sse_encode_bool(self.batched, serializer);
    sse_encode_String(self.tagHex, serializer);
    sse_encode_String(self.objectRootHex, serializer);
    sse_encode_opt_String(self.senderPubkeyHex, serializer);
    sse_encode_String(self.nonceHex, serializer);
    sse_encode_usize(self.ciphertextLen, serializer);
    sse_encode_usize(self.paddingLen, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_shard_meta(ShardMeta self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.version, serializer);
    sse_encode_u_16(self.namespace, serializer);
    sse_encode_u_32(self.epoch, serializer);
    sse_encode_String(self.tagHex, serializer);
    sse_encode_String(self.objectRootHex, serializer);
    sse_encode_u_16(self.k, serializer);
    sse_encode_u_16(self.n, serializer);
    sse_encode_u_16(self.index, serializer);
    sse_encode_usize(self.payloadLen, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
